### ISSUE TITLE
DH keypair exception

### ISSUE THREAD

**Issue by abhiit61** [clickntap/Vimeo#10]
Following below is the exception i am facing while uploading the video to vimeo.
Also the exception does not occur frequently. But i wanna know how can I solve it.

javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1904)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1862)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1845)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1366)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:290)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:259)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at com.clickntap.vimeo.Vimeo.apiRequest(Vimeo.java:247)
	at com.clickntap.vimeo.Vimeo.uploadVideo(Vimeo.java:109)
	at com.clickntap.vimeo.Vimeo.addVideo(Vimeo.java:123)

**Comment by chaotic-studio** [comment]
Hello abhiit61!

First of all, please provide the JDK Version you are using in future questions/issues. When it comes to Runtime Exceptions, this is information is very often crucial.

I did some research about the error and believe that your issue could possibly result from the JDK 7 behaviour described here:

https://confluence.atlassian.com/plugins/servlet/mobile#content/view/715129360

http://stackoverflow.com/questions/10687200/java-7-and-could-not-generate-dh-keypair

The cause is nicely described in the first link. Allow me to quote:

"From the Apache article, beginning with version 2.4.7, mod_ssl will use DH parameters which include primes with lengths of more than 1024 bits. However, Java 7 and earlier limit their support for DH prime sizes to a maximum of 1024 bits."

Please try the solutions provided in the two articles I linked and inform us about the result afterwards.

Best Regards
Martin

**Comment by josesanpedro** [comment]
Hi there, im havign the same issue using JDK 8. Started to occurs out of nowhere. One day was working fine and the other was broken.

Any help? Thanks!
